### ISSUE TITLE
What is deleted-dict.txt?

### ISSUE THREAD

**Issue by spotlightishere** [games647/Minecraft-Blocked-Servers#3]
As the title suggests, what is it? Do servers contained in deleted-dict.txt get blocked from chat, or is that yet another block list?

**Comment by TuxCoding** [comment]
It's a list of servers which are checked against the blocked-server list. In the case Mojang bans more servers we have to rerun the check. 

Because of hashing it's only possible to check it in one way. So we need a directory of all server addresses we could check. 

Plain text -> Hash

Another solution would be brute forcing (try out every possible character combination), but there would be too many combinations. So it's better to have a directory.

**Comment by spotlightishere** [comment]
Makes sense. I was hoping it wasn't a list of blocked strings in chat xD 

Thank you for the list, by the way!
